# Generated by Django 5.0.6 on 2024-05-31 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="route_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
