# Generated by Django 5.0.6 on 2024-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0002_newslettersubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("difficult", "Difficult"),
                ],
                default="moderate",
                max_length=10,
            ),
        ),
    ]
