# Generated by Django 3.2.25 on 2024-05-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
