# Generated by Django 5.0.6 on 2024-06-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0003_post_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
